version: "2"

run:
  timeout: 5m

linters:
  enable:
    - copyloopvar
    - durationcheck
    - errcheck
    - forcetypeassert
    - godot
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usetesting

  settings:
    errcheck:
      exclude-functions:
        - (io.ReadCloser).Close # ignore close error for http response body

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
