version: 2

run:
  timeout: 5m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - 'Error return value of `resp.Body.Close` is not checked'
    - 'Error return value of `response.Body.Close` is not checked'
    - 'ST1023: should omit type []*hookdeck.Rule from declaration; it will be inferred from the right-hand side'
    - 'ST1023: should omit type []rule from declaration; it will be inferred from the right-hand side'
    - 'ST1023: should omit type map[string]any from declaration; it will be inferred from the right-hand side'

linters:
  disable-all: true
  enable:
    - copyloopvar
    - durationcheck
    - errcheck
    - forcetypeassert
    - godot
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - usetesting

format:
  enable:
    - gofmt

output:
  format: colored-line-number
  sort-results: true