// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/hookdeck/hookdeck-go-sdk/internal"
)

type AttemptListRequest struct {
	EventId []*string                  `json:"-" url:"event_id,omitempty"`
	OrderBy *AttemptListRequestOrderBy `json:"-" url:"order_by,omitempty"`
	Dir     *AttemptListRequestDir     `json:"-" url:"dir,omitempty"`
	Limit   *int                       `json:"-" url:"limit,omitempty"`
	Next    *string                    `json:"-" url:"next,omitempty"`
	Prev    *string                    `json:"-" url:"prev,omitempty"`
}

type EventAttemptPaginatedResult struct {
	Pagination *SeekPagination `json:"pagination,omitempty" url:"pagination,omitempty"`
	Count      *int            `json:"count,omitempty" url:"count,omitempty"`
	Models     []*EventAttempt `json:"models,omitempty" url:"models,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EventAttemptPaginatedResult) GetPagination() *SeekPagination {
	if e == nil {
		return nil
	}
	return e.Pagination
}

func (e *EventAttemptPaginatedResult) GetCount() *int {
	if e == nil {
		return nil
	}
	return e.Count
}

func (e *EventAttemptPaginatedResult) GetModels() []*EventAttempt {
	if e == nil {
		return nil
	}
	return e.Models
}

func (e *EventAttemptPaginatedResult) GetExtraProperties() map[string]interface{} {
	return e.extraProperties
}

func (e *EventAttemptPaginatedResult) UnmarshalJSON(data []byte) error {
	type unmarshaler EventAttemptPaginatedResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EventAttemptPaginatedResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EventAttemptPaginatedResult) String() string {
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

type AttemptListRequestDir string

const (
	AttemptListRequestDirAsc  AttemptListRequestDir = "asc"
	AttemptListRequestDirDesc AttemptListRequestDir = "desc"
)

func NewAttemptListRequestDirFromString(s string) (AttemptListRequestDir, error) {
	switch s {
	case "asc":
		return AttemptListRequestDirAsc, nil
	case "desc":
		return AttemptListRequestDirDesc, nil
	}
	var t AttemptListRequestDir
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AttemptListRequestDir) Ptr() *AttemptListRequestDir {
	return &a
}

type AttemptListRequestOrderBy string

const (
	AttemptListRequestOrderByCreatedAt AttemptListRequestOrderBy = "created_at"
)

func NewAttemptListRequestOrderByFromString(s string) (AttemptListRequestOrderBy, error) {
	switch s {
	case "created_at":
		return AttemptListRequestOrderByCreatedAt, nil
	}
	var t AttemptListRequestOrderBy
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AttemptListRequestOrderBy) Ptr() *AttemptListRequestOrderBy {
	return &a
}
