// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	core "github.com/hookdeck/hookdeck-go-sdk/core"
)

// Bad Request
type BadRequestError struct {
	*core.APIError
	Body *ApiErrorResponse
}

func (b *BadRequestError) UnmarshalJSON(data []byte) error {
	var body *ApiErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	b.StatusCode = 400
	b.Body = body
	return nil
}

func (b *BadRequestError) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.Body)
}

func (b *BadRequestError) Unwrap() error {
	return b.APIError
}

// Gone
type GoneError struct {
	*core.APIError
	Body *ApiErrorResponse
}

func (g *GoneError) UnmarshalJSON(data []byte) error {
	var body *ApiErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	g.StatusCode = 410
	g.Body = body
	return nil
}

func (g *GoneError) MarshalJSON() ([]byte, error) {
	return json.Marshal(g.Body)
}

func (g *GoneError) Unwrap() error {
	return g.APIError
}

// Not Found
type NotFoundError struct {
	*core.APIError
	Body *ApiErrorResponse
}

func (n *NotFoundError) UnmarshalJSON(data []byte) error {
	var body *ApiErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	n.StatusCode = 404
	n.Body = body
	return nil
}

func (n *NotFoundError) MarshalJSON() ([]byte, error) {
	return json.Marshal(n.Body)
}

func (n *NotFoundError) Unwrap() error {
	return n.APIError
}

// Unprocessable Entity
type UnprocessableEntityError struct {
	*core.APIError
	Body *ApiErrorResponse
}

func (u *UnprocessableEntityError) UnmarshalJSON(data []byte) error {
	var body *ApiErrorResponse
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.StatusCode = 422
	u.Body = body
	return nil
}

func (u *UnprocessableEntityError) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

func (u *UnprocessableEntityError) Unwrap() error {
	return u.APIError
}
