// This file was auto-generated by Fern from our API Definition.

package api

import (
	json "encoding/json"
	fmt "fmt"
	core "github.com/hookdeck/hookdeck-go-sdk/core"
	internal "github.com/hookdeck/hookdeck-go-sdk/internal"
	time "time"
)

type IgnoredEventBulkRetryCreateRequest struct {
	// Filter by the bulk retry ignored event query object
	Query *core.Optional[IgnoredEventBulkRetryCreateRequestQuery] `json:"query,omitempty" url:"-"`
}

type IgnoredEventBulkRetryListRequest struct {
	CancelledAt       *time.Time                               `json:"-" url:"cancelled_at,omitempty"`
	CompletedAt       *time.Time                               `json:"-" url:"completed_at,omitempty"`
	CreatedAt         *time.Time                               `json:"-" url:"created_at,omitempty"`
	Id                []*string                                `json:"-" url:"id,omitempty"`
	QueryPartialMatch *bool                                    `json:"-" url:"query_partial_match,omitempty"`
	InProgress        *bool                                    `json:"-" url:"in_progress,omitempty"`
	OrderBy           *IgnoredEventBulkRetryListRequestOrderBy `json:"-" url:"order_by,omitempty"`
	Dir               *IgnoredEventBulkRetryListRequestDir     `json:"-" url:"dir,omitempty"`
	Limit             *int                                     `json:"-" url:"limit,omitempty"`
	Next              *string                                  `json:"-" url:"next,omitempty"`
	Prev              *string                                  `json:"-" url:"prev,omitempty"`
}

// Filter by the bulk retry ignored event query object
type IgnoredEventBulkRetryCreateRequestQuery struct {
	// The cause of the ignored event
	Cause *IgnoredEventBulkRetryCreateRequestQueryCause `json:"cause,omitempty" url:"cause,omitempty"`
	// Connection ID of the ignored event
	WebhookId *IgnoredEventBulkRetryCreateRequestQueryWebhookId `json:"webhook_id,omitempty" url:"webhook_id,omitempty"`
	// The associated transformation ID (only applicable to the cause `TRANSFORMATION_FAILED`)
	TransformationId *string `json:"transformation_id,omitempty" url:"transformation_id,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IgnoredEventBulkRetryCreateRequestQuery) GetCause() *IgnoredEventBulkRetryCreateRequestQueryCause {
	if i == nil {
		return nil
	}
	return i.Cause
}

func (i *IgnoredEventBulkRetryCreateRequestQuery) GetWebhookId() *IgnoredEventBulkRetryCreateRequestQueryWebhookId {
	if i == nil {
		return nil
	}
	return i.WebhookId
}

func (i *IgnoredEventBulkRetryCreateRequestQuery) GetTransformationId() *string {
	if i == nil {
		return nil
	}
	return i.TransformationId
}

func (i *IgnoredEventBulkRetryCreateRequestQuery) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *IgnoredEventBulkRetryCreateRequestQuery) UnmarshalJSON(data []byte) error {
	type unmarshaler IgnoredEventBulkRetryCreateRequestQuery
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = IgnoredEventBulkRetryCreateRequestQuery(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IgnoredEventBulkRetryCreateRequestQuery) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// The cause of the ignored event
type IgnoredEventBulkRetryCreateRequestQueryCause struct {
	String     string
	StringList []string

	typ string
}

func NewIgnoredEventBulkRetryCreateRequestQueryCauseFromString(value string) *IgnoredEventBulkRetryCreateRequestQueryCause {
	return &IgnoredEventBulkRetryCreateRequestQueryCause{typ: "String", String: value}
}

func NewIgnoredEventBulkRetryCreateRequestQueryCauseFromStringList(value []string) *IgnoredEventBulkRetryCreateRequestQueryCause {
	return &IgnoredEventBulkRetryCreateRequestQueryCause{typ: "StringList", StringList: value}
}

func (i *IgnoredEventBulkRetryCreateRequestQueryCause) GetString() string {
	if i == nil {
		return ""
	}
	return i.String
}

func (i *IgnoredEventBulkRetryCreateRequestQueryCause) GetStringList() []string {
	if i == nil {
		return nil
	}
	return i.StringList
}

func (i *IgnoredEventBulkRetryCreateRequestQueryCause) UnmarshalJSON(data []byte) error {
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		i.typ = "String"
		i.String = valueString
		return nil
	}
	var valueStringList []string
	if err := json.Unmarshal(data, &valueStringList); err == nil {
		i.typ = "StringList"
		i.StringList = valueStringList
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, i)
}

func (i IgnoredEventBulkRetryCreateRequestQueryCause) MarshalJSON() ([]byte, error) {
	if i.typ == "String" || i.String != "" {
		return json.Marshal(i.String)
	}
	if i.typ == "StringList" || i.StringList != nil {
		return json.Marshal(i.StringList)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", i)
}

type IgnoredEventBulkRetryCreateRequestQueryCauseVisitor interface {
	VisitString(string) error
	VisitStringList([]string) error
}

func (i *IgnoredEventBulkRetryCreateRequestQueryCause) Accept(visitor IgnoredEventBulkRetryCreateRequestQueryCauseVisitor) error {
	if i.typ == "String" || i.String != "" {
		return visitor.VisitString(i.String)
	}
	if i.typ == "StringList" || i.StringList != nil {
		return visitor.VisitStringList(i.StringList)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", i)
}

// Connection ID of the ignored event
type IgnoredEventBulkRetryCreateRequestQueryWebhookId struct {
	String     string
	StringList []string

	typ string
}

func NewIgnoredEventBulkRetryCreateRequestQueryWebhookIdFromString(value string) *IgnoredEventBulkRetryCreateRequestQueryWebhookId {
	return &IgnoredEventBulkRetryCreateRequestQueryWebhookId{typ: "String", String: value}
}

func NewIgnoredEventBulkRetryCreateRequestQueryWebhookIdFromStringList(value []string) *IgnoredEventBulkRetryCreateRequestQueryWebhookId {
	return &IgnoredEventBulkRetryCreateRequestQueryWebhookId{typ: "StringList", StringList: value}
}

func (i *IgnoredEventBulkRetryCreateRequestQueryWebhookId) GetString() string {
	if i == nil {
		return ""
	}
	return i.String
}

func (i *IgnoredEventBulkRetryCreateRequestQueryWebhookId) GetStringList() []string {
	if i == nil {
		return nil
	}
	return i.StringList
}

func (i *IgnoredEventBulkRetryCreateRequestQueryWebhookId) UnmarshalJSON(data []byte) error {
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		i.typ = "String"
		i.String = valueString
		return nil
	}
	var valueStringList []string
	if err := json.Unmarshal(data, &valueStringList); err == nil {
		i.typ = "StringList"
		i.StringList = valueStringList
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, i)
}

func (i IgnoredEventBulkRetryCreateRequestQueryWebhookId) MarshalJSON() ([]byte, error) {
	if i.typ == "String" || i.String != "" {
		return json.Marshal(i.String)
	}
	if i.typ == "StringList" || i.StringList != nil {
		return json.Marshal(i.StringList)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", i)
}

type IgnoredEventBulkRetryCreateRequestQueryWebhookIdVisitor interface {
	VisitString(string) error
	VisitStringList([]string) error
}

func (i *IgnoredEventBulkRetryCreateRequestQueryWebhookId) Accept(visitor IgnoredEventBulkRetryCreateRequestQueryWebhookIdVisitor) error {
	if i.typ == "String" || i.String != "" {
		return visitor.VisitString(i.String)
	}
	if i.typ == "StringList" || i.StringList != nil {
		return visitor.VisitStringList(i.StringList)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", i)
}

type IgnoredEventBulkRetryListRequestDir string

const (
	IgnoredEventBulkRetryListRequestDirAsc  IgnoredEventBulkRetryListRequestDir = "asc"
	IgnoredEventBulkRetryListRequestDirDesc IgnoredEventBulkRetryListRequestDir = "desc"
)

func NewIgnoredEventBulkRetryListRequestDirFromString(s string) (IgnoredEventBulkRetryListRequestDir, error) {
	switch s {
	case "asc":
		return IgnoredEventBulkRetryListRequestDirAsc, nil
	case "desc":
		return IgnoredEventBulkRetryListRequestDirDesc, nil
	}
	var t IgnoredEventBulkRetryListRequestDir
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (i IgnoredEventBulkRetryListRequestDir) Ptr() *IgnoredEventBulkRetryListRequestDir {
	return &i
}

type IgnoredEventBulkRetryListRequestOrderBy string

const (
	IgnoredEventBulkRetryListRequestOrderByCreatedAt IgnoredEventBulkRetryListRequestOrderBy = "created_at"
)

func NewIgnoredEventBulkRetryListRequestOrderByFromString(s string) (IgnoredEventBulkRetryListRequestOrderBy, error) {
	switch s {
	case "created_at":
		return IgnoredEventBulkRetryListRequestOrderByCreatedAt, nil
	}
	var t IgnoredEventBulkRetryListRequestOrderBy
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (i IgnoredEventBulkRetryListRequestOrderBy) Ptr() *IgnoredEventBulkRetryListRequestOrderBy {
	return &i
}

type IgnoredEventBulkRetryPlanResponse struct {
	// Number of batches required to complete the bulk retry
	EstimatedBatch *int `json:"estimated_batch,omitempty" url:"estimated_batch,omitempty"`
	// Number of estimated events to be retried
	EstimatedCount *int `json:"estimated_count,omitempty" url:"estimated_count,omitempty"`
	// Progression of the batch operations, values 0 - 1
	Progress *float64 `json:"progress,omitempty" url:"progress,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IgnoredEventBulkRetryPlanResponse) GetEstimatedBatch() *int {
	if i == nil {
		return nil
	}
	return i.EstimatedBatch
}

func (i *IgnoredEventBulkRetryPlanResponse) GetEstimatedCount() *int {
	if i == nil {
		return nil
	}
	return i.EstimatedCount
}

func (i *IgnoredEventBulkRetryPlanResponse) GetProgress() *float64 {
	if i == nil {
		return nil
	}
	return i.Progress
}

func (i *IgnoredEventBulkRetryPlanResponse) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *IgnoredEventBulkRetryPlanResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler IgnoredEventBulkRetryPlanResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = IgnoredEventBulkRetryPlanResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IgnoredEventBulkRetryPlanResponse) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}
