// This file was auto-generated by Fern from our API Definition.

package api

import (
	time "time"

	core "github.com/hookdeck/hookdeck-go-sdk/core"
	internal "github.com/hookdeck/hookdeck-go-sdk/internal"
)

// Optional initializes an optional field.
func Optional[T any](value T) *core.Optional[T] {
	return &core.Optional[T]{
		Value: value,
	}
}

// Null initializes an optional field that will be sent as
// an explicit null value.
func Null[T any]() *core.Optional[T] {
	return &core.Optional[T]{
		Null: true,
	}
}

// NewDateTimeFromOptional returns a new *DateTime from the given optional.
func NewDateTimeFromOptional(optional *core.Optional[time.Time]) *internal.DateTime {
	if optional == nil {
		return nil
	}
	return internal.NewDateTime(optional.Value)
}

// OptionalOrNull initializes an optional field, setting the value
// to an explicit null if the value is nil.
func OptionalOrNull[T any](value *T) *core.Optional[T] {
	if value == nil {
		return Null[T]()
	}
	return Optional(*value)
}
